use groups_students;
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Java');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Python');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'С++');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'C#');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Go');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Fortran');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'JavaScript');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'РНР');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Ruby');

insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Christian', 'Bauer');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Gavin', 'King');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Gary', 'Gregory');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Bruce', 'Eckel');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Brian', 'Goetz');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Tim', 'Peierls');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Joshua', 'Bloch');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Joseph', 'Bowbeer');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'David', 'Holmes');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Doug', 'Lea');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Raoul-Gabriel', 'Urma');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Mario', 'Fusco');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Alan', 'Mycroft');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Scott', 'Oaks');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Elena','Homenko');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Egor','Lenko');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Alexander','Beztsennyi');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Alexander','Kucheryavyi');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Zahar','Morozov');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Anastasia','Shestoperova');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Eduard','Plastun');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'German', 'Martin');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Danya', 'Jordan');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Iegor', 'Jackson');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Oleg', 'Grant');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'John', 'Evans');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Lesha', 'Stone');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Gleb', 'Roberts');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Vika', 'Mills');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Dasha', 'Lewis');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Viktoria', 'Morgan');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Petya', 'Florence');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Andrei', 'Campbell');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Cristobal', 'Bronte');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Fabio', 'Bell');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Gijs', 'Adams');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Johannes', 'Williams');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Frankie', 'Peters');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Belle', 'Davis');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Greta', 'Collins');
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Hazel', 'Bradley');

insert into groups_students_table values (1, 1);
insert into groups_students_table values (2, 2);
insert into groups_students_table values (3, 3);
insert into groups_students_table values (4, 4);
insert into groups_students_table values (5, 5);
insert into groups_students_table values (6, 6);
insert into groups_students_table values (7, 7);
insert into groups_students_table values (8, 8);
insert into groups_students_table values (9, 9);
insert into groups_students_table values (10, 9);
insert into groups_students_table values (11, 8);
insert into groups_students_table values (12, 7);
insert into groups_students_table values (13, 6);
insert into groups_students_table values (14, 5);
insert into groups_students_table values (15, 4);
insert into groups_students_table values (16, 3);
insert into groups_students_table values (17, 2);
insert into groups_students_table values (18, 1);
insert into groups_students_table values (19, 1);
insert into groups_students_table values (20, 2);
insert into groups_students_table values (21, 3);
insert into groups_students_table values (22, 7);
insert into groups_students_table values (23, 3);
insert into groups_students_table values (24, 4);
insert into groups_students_table values (25, 9);
insert into groups_students_table values (26, 1);
insert into groups_students_table values (27, 2);
insert into groups_students_table values (28, 6);
insert into groups_students_table values (29, 4);
insert into groups_students_table values (30, 8);
insert into groups_students_table values (31, 1);
insert into groups_students_table values (32, 7);
insert into groups_students_table values (33, 3);
insert into groups_students_table values (34, 4);
insert into groups_students_table values (35, 9);
insert into groups_students_table values (36, 1);
insert into groups_students_table values (37, 2);
insert into groups_students_table values (38, 5);
insert into groups_students_table values (39, 4);
insert into groups_students_table values (40, 8);
insert into groups_students_table values (41, 4);