use groups_students;
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Java');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Python');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'С++');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'C#');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Go');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Fortran');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'JavaScript');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'РНР');
insert into groups_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Ruby');

insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Christian', 'Bauer', 1);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Gavin', 'King', 2);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Gary', 'Gregory', 3);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Bruce', 'Eckel', 4);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Brian', 'Goetz', 5);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Tim', 'Peierls', 6);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Joshua', 'Bloch', 7);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Joseph', 'Bowbeer', 8);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'David', 'Holmes', 9);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Doug', 'Lea', 9);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Raoul-Gabriel', 'Urma', 6);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Mario', 'Fusco', 3);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Alan', 'Mycroft', 9);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Scott', 'Oaks', 2);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Elena','Homenko', 3);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Egor','Lenko', 4);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Alexander','Beztsennyi', 9);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Alexander','Kucheryavyi', 7);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Zahar','Morozov', 4);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Anastasia','Shestoperova', 7);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Eduard','Plastun', 2);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'German', 'Martin', 9);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Danya', 'Jordan', 6);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Iegor', 'Jackson', 8);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Oleg', 'Grant', 3);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'John', 'Evans', 4);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Lesha', 'Stone', 2);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Gleb', 'Roberts', 3);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Vika', 'Mills', 6);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Dasha', 'Lewis', 1);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Viktoria', 'Morgan', 4);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Petya', 'Florence', 2);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Andrei', 'Campbell', 6);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Cristobal', 'Bronte', 1);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Fabio', 'Bell', 2);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Gijs', 'Adams', 6);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Johannes', 'Williams', 7);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Frankie', 'Peters', 3);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Belle', 'Davis', 1);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Greta', 'Collins', 6);
insert into students_table values (default, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Hazel', 'Bradley', 7);